"""
    Lethean Binary API

    Functionality to simplify using LTHN  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Contact: contact@lethean.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import letheanSDP
from letheanSDP.api.vpn_api import VpnApi  # noqa: E501


class TestVpnApi(unittest.TestCase):
    """VpnApi unit test stubs"""

    def setUp(self):
        self.api = VpnApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_start_letheand(self):
        """Test case for start_letheand

        """
        pass


if __name__ == '__main__':
    unittest.main()
