"""
    Lethean Binary API

    Functionality to simplify using LTHN  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Contact: contact@lethean.io
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "letheanSDP"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="Lethean Binary API",
    author="Lethean VPN",
    author_email="contact@lethean.io",
    url="https://lt.hn/en/sdk/python",
    keywords=["OpenAPI", "OpenAPI-Generator", "Lethean Binary API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="GPLv3",
    long_description="""\
    Functionality to simplify using LTHN  # noqa: E501
    """
)
